# Generated by Django 4.2 on 2026-01-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma_payments', '0002_auto_20200817_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionagreement',
            name='payment_provider',
            field=models.CharField(
                choices=[('cybersource', 'cybersource'), ('stripe', 'stripe')],
                default='cybersource',
                help_text='Which payment provider backs this agreement (CyberSource or Stripe).',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='subscriptionagreement',
            name='payment_provider',
            field=models.CharField(
                choices=[('cybersource', 'cybersource'), ('stripe', 'stripe')],
                default='cybersource',
                help_text='Which payment provider backs this agreement (CyberSource or Stripe).',
                max_length=20
            ),
        ),
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_session_id', models.CharField(help_text='Stripe Checkout Session id (cs_...)', max_length=255, unique=True)),
                ('livemode', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('subscription_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_checkout_session', to='perma_payments.subscriptionagreement')),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Stripe Event id (evt_...)', max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('api_version', models.CharField(blank=True, max_length=50, null=True)),
                ('livemode', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, help_text='Event creation time as reported by Stripe.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('payload_encrypted', models.BinaryField(help_text='The full webhook payload, encrypted, in case we ever need it.')),
                ('encryption_key_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(help_text='Stripe Subscription id (sub_...)', max_length=255, unique=True)),
                ('customer_id', models.CharField(blank=True, default='', help_text='Stripe Customer id (cus_...)', max_length=255)),
                ('livemode', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('subscription_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscription', to='perma_payments.subscriptionagreement')),
            ],
        ),
    ]

